### ISSUE TITLE
Commands / how-to on de-registering a worker?

### ISSUE THREAD

**Issue by cjcjameson** [concourse/tsa#3]
We're interested in taking one of our workers offline for further investigation. Are there instructions somewhere about how to do this with TSA?

**Comment by cjcjameson** [comment]
Short answer: "you could stop the beacon on the worker"

**Comment by chendrix** [comment]
I'm going to close this, but I've tagged your tracker story with `operability` and `docs` so that we can think about it when we focus more on those themes.
