### ISSUE TITLE
TSA does not reload authorized_keys when file changes without restart

### ISSUE THREAD

**Issue by iSynaptic** [concourse/tsa#5]
When changing the authorized_keys file to dynamically add a new worker, the TSA doesn't recognize the new key unless the TSA is restarted.  This makes dynamically provisioning a worker via automation difficult.

Please add the ability to automatically pick up changes to the authorized_key files or an API/fly command to trigger the reload.

**Comment by chendrix** [comment]
Moved to concourse/concourse#1105
